spring.application.name=bank-api


#spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.flywaydb=DEBUG

# Development only. Production uses AWS Secrets Manager
jwt.secret=4K8vZQ2xN9LmP7RsT5UwX8YbE3HdJ6NcFaG1HiKoLpMv
jwt.expiration=3600000

springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
# Show detailed health information
management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}

management.otlp.metrics.export.enabled=false

bank.rate-limit.transfer.limit=10
bank.rate-limit.transfer.window=60