aws.secrets-manager.rds-secret-arn=${RDS_SECRET_ARN}
spring.datasource.url=jdbc:postgresql://bank-api-prod-postgres.cx6yw006cgkb.eu-central-1.rds.amazonaws.com:5432/bankdb

spring.config.import=aws-secretsmanager:bank-api/jwt-secret

spring.kafka.bootstrap-servers=${MSK_BOOTSTRAP_SERVERS}

spring.kafka.admin.auto-create=true

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=AWS_MSK_IAM
spring.kafka.properties.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
spring.kafka.properties.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

bank.kafka.topics.transfer-completed=transfer-completed
bank.kafka.topics.transfer-completed-dlt=transfer-completed-dlt

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.ssl.enabled=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.bank.bankapi.kafka.event

spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true
management.observations.annotations.enabled=true


management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces
management.tracing.sampling.probability=1.0

management.otlp.metrics.export.enabled=false

