apiVersion: v1
kind: Service
metadata:
  name: bank-api
  namespace: bank-api
spec:
  selector:
    app: bank-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP