apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          args:
            - "--config=/etc/otelcol/otel-collector-config.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otelcol
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config

---

apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: bank-api
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP